spring.application.name=inventario

# Oracle DataSource
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=inventario_user
spring.datasource.password=inventario_pass

# JPA — ddl-auto=validate porque Flyway gestiona el esquema
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration